services:
  - type: web
    name: lms-stt-sp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
      - key: INITIAL_USER_PASSWORD
        sync: false
